# Generated by Django 4.2.24 on 2025-09-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-fecha_ingreso'], 'permissions': (('authorize_visit', 'Puede autorizar visitas'), ('view_visits_all', 'Puede ver todas las visitas')), 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
    ]
