# Generated by Django 4.2.24 on 2025-09-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-creado'], 'permissions': (('mark_pago', 'Puede marcar pago como completado'), ('view_pago_all', 'Puede ver todos los pagos')), 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
