# Generated by Django 4.2.24 on 2025-09-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('administrar_modulos', 'Puede administrar módulos (permiso global de módulo)'), ('aprobar_reservas', 'Puede aprobar reservas'), ('gestionar_pagos', 'Puede gestionar pagos')), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
