# Generated by Django 4.2.24 on 2025-09-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartamento',
            options={'ordering': ['numero'], 'permissions': (('manage_apartamentos', 'Puede gestionar apartamentos'),), 'verbose_name': 'Apartamento', 'verbose_name_plural': 'Apartamentos'},
        ),
    ]
