# Generated by Django 4.2.24 on 2025-09-29 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Apartamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('visitante_nombre', models.CharField(max_length=200, verbose_name='Nombre visitante')),
                ('visitante_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento visitante')),
                ('visitante_telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('placa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa vehículo')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha ingreso')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha salida')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo')),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autorizado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='Apartamentos.apartamento', verbose_name='Apartamento a visitar')),
                ('autoriza_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('ingresado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por (portería)')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'visits',
                'ordering': ['-fecha_ingreso'],
                'permissions': (('authorize_visit', 'Puede autorizar visitas'), ('view_visits_all', 'Puede ver todas las visitas')),
            },
        ),
    ]
