# Generated by Django 4.2.24 on 2025-09-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'permissions': (('approve_reserva', 'Puede aprobar o rechazar reservas'), ('view_reserva_all', 'Puede ver todas las reservas')), 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
