# Generated by Django 4.2.24 on 2025-09-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero', models.CharField(db_index=True, max_length=20, verbose_name='Número')),
                ('torre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Torre / Bloque')),
                ('piso', models.IntegerField(blank=True, null=True, verbose_name='Piso')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo (ej. 2 habitaciones)')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Área (m2)')),
                ('ocupantes', models.PositiveIntegerField(default=1, verbose_name='Número de ocupantes')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'db_table': 'apartamentos',
                'ordering': ['numero'],
                'permissions': (('manage_apartamentos', 'Puede gestionar apartamentos'),),
            },
        ),
    ]
