# Generated by Django 4.2.24 on 2025-09-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha finalizado')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo estimado')),
                ('costo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo final')),
                ('estado', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('SCHEDULED', 'Programado'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='REQUESTED', max_length=20, verbose_name='Estado')),
                ('notificar_residentes', models.BooleanField(default=True, verbose_name='Notificar a residentes')),
                ('comentario_admin', models.TextField(blank=True, null=True, verbose_name='Comentario administración')),
            ],
            options={
                'verbose_name': 'Solicitud de mantenimiento',
                'verbose_name_plural': 'Solicitudes de mantenimiento',
                'db_table': 'maintenance_requests',
                'ordering': ['-creado'],
                'permissions': (('assign_maintenance', 'Puede asignar solicitudes de mantenimiento'), ('complete_maintenance', 'Puede marcar mantenimiento como completado'), ('view_maintenance_all', 'Puede ver todas las solicitudes de mantenimiento')),
            },
        ),
    ]
