# Generated by Django 4.2.24 on 2025-09-29 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reservas', '0001_initial'),
        ('Mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='Reservas.commonarea', verbose_name='Área común (si aplica)'),
        ),
    ]
