# Generated by Django 4.2.24 on 2025-09-30 21:32

import Mantenimiento.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mantenimiento', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=Mantenimiento.models.maintenance_attachment_path, verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('tamaño', models.IntegerField(help_text='Tamaño en bytes', verbose_name='Tamaño (bytes)')),
                ('tipo_contenido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de contenido')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('es_evidencia_final', models.BooleanField(default=False, help_text='Marca si es evidencia de trabajo completado', verbose_name='Es evidencia final')),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Mantenimiento.maintenancerequest', verbose_name='Solicitud de mantenimiento')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de mantenimiento',
                'verbose_name_plural': 'Adjuntos de mantenimiento',
                'db_table': 'maintenance_attachments',
                'ordering': ['-subido_en'],
            },
        ),
    ]
