# Generated by Django 4.2.24 on 2025-09-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(choices=[('PETITION', 'Petición'), ('COMPLAINT', 'Queja'), ('CLAIM', 'Reclamo'), ('SUGGESTION', 'Sugerencia')], max_length=20, verbose_name='Tipo')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En progreso'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('respuesta', models.TextField(blank=True, null=True, verbose_name='Respuesta del administrador')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha respuesta')),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs', to='Apartments.apartamento', verbose_name='Apartamento relacionado')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
                'db_table': 'pqrs',
                'ordering': ['-creado'],
            },
        ),
    ]
