# Generated by Django 4.2.24 on 2025-09-29 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pqrs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_respondidos', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs', to=settings.AUTH_USER_MODEL, verbose_name='Remitente'),
        ),
    ]
