# Generated by Django 4.2.24 on 2025-09-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pqrs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqrs',
            options={'ordering': ['-creado'], 'permissions': (('respond_pqrs', 'Puede responder y cerrar PQRS'), ('view_pqrs_all', 'Puede ver todas las PQRS')), 'verbose_name': 'PQRS', 'verbose_name_plural': 'PQRS'},
        ),
    ]
