# Generated by Django 4.2.24 on 2025-09-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-creado'], 'permissions': (('assign_maintenance', 'Puede asignar solicitudes de mantenimiento'), ('complete_maintenance', 'Puede marcar mantenimiento como completado'), ('view_maintenance_all', 'Puede ver todas las solicitudes de mantenimiento')), 'verbose_name': 'Solicitud de mantenimiento', 'verbose_name_plural': 'Solicitudes de mantenimiento'},
        ),
    ]
