# Generated by Django 4.2.24 on 2025-09-29 22:42

import Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('archivo', models.FileField(max_length=400, upload_to=Base.models.archivo_upload_to, verbose_name='Archivo')),
                ('ruta_archivo', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ruta de archivo')),
                ('nombre_archivo', models.CharField(max_length=300, verbose_name='Nombre del archivo')),
                ('url_archivo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL del archivo')),
                ('archivo_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID del archivo')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'base_archivo',
                'ordering': ['-creado'],
            },
        ),
    ]
