# Generated by Django 4.2.24 on 2025-09-29 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Apartamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('capacidad', models.PositiveIntegerField(default=1, verbose_name='Capacidad (opcional)')),
            ],
            options={
                'verbose_name': 'Área común',
                'verbose_name_plural': 'Áreas comunes',
                'db_table': 'common_areas',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y hora inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y hora fin')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('notas', models.TextField(blank=True, null=True)),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='Apartamentos.apartamento', verbose_name='Apartamento')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservations',
                'ordering': ['-creado'],
                'permissions': (('approve_reserva', 'Puede aprobar o rechazar reservas'), ('view_reserva_all', 'Puede ver todas las reservas')),
            },
        ),
    ]
